before:
  hooks:
    - go vet ./...
    - go test ./...
    - go mod download
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  ldflags:
    - -s -w -X github.com/mittwald/spacectl/buildinfo.Version={{.Tag}} -X github.com/mittwald/spacectl/buildinfo.Hash={{.ShortCommit}} -X github.com/mittwald/spacectl/buildinfo.BuildDate={{.Date}}
  goos:
  - darwin
  - linux
  - windows
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brew:
  github:
    owner: mittwald
    name: homebrew-spaces
  commit_author:
    name: Martin Helmich
    email: m.helmich@mittwald.de
  # Your app's homepage.
  homepage: "https://www.spaces.de/"
  # Your app's description.
  description: "CLI client for Mittwald SPACES"