language: go

go:
- 1.11

env:
  global:
    - GO111MODULE=on
    - CGO_ENABLED=0

script:
  - bash <(wget -qO- https://git.io/goreleaser) --snapshot --skip-publish --rm-dist

deploy:
- provider: script
  skip_cleanup: true
  script: bash <(wget -qO- https://git.io/goreleaser)
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux